apiVersion: apps/v1  # <-- Fix this line
kind: ReplicaSet
metadata:
  name: foodiesreplicaset
spec:
  replicas: 2
  selector:
    matchLabels:
      app: foodies
      version: "1.0"
  template:  # <-- This line should be indented properly under 'spec'
    metadata:
      labels:
        app: foodies
        version: "1.0"
    spec:
      containers:
        - name: foodies
          image: saipavangockerhub/foodiesreplica:1.0
          ports:
            - name: tomcatport
              containerPort: 8080
              protocol: TCP

          